import { BForm } from 'bootstrap-vue';
import { BFormInput } from 'bootstrap-vue';
import { BFormCheckbox } from 'bootstrap-vue';
import { BFormCheckboxGroup } from 'bootstrap-vue';
import { BFormGroup } from 'bootstrap-vue';
import { BProgress } from 'bootstrap-vue';
import { BProgressBar } from 'bootstrap-vue';
import { BPagination } from 'bootstrap-vue';
import { BButton } from 'bootstrap-vue';
import { BNavbar } from 'bootstrap-vue';
import { BNavbarNav } from 'bootstrap-vue';
import { BNavbarBrand } from 'bootstrap-vue';
import { BNavbarToggle } from 'bootstrap-vue';
import { BNavItem } from 'bootstrap-vue';
import { BNavItemDropdown } from 'bootstrap-vue';
import { BCollapse } from 'bootstrap-vue';
import { BBadge } from 'bootstrap-vue';
import { BDropdown } from 'bootstrap-vue';
import { BDropdownItem } from 'bootstrap-vue';
import { BLink } from 'bootstrap-vue';
import { BAlert } from 'bootstrap-vue';
import { BModal } from 'bootstrap-vue';
import { VBModal } from 'bootstrap-vue';
import { BFormTextarea } from 'bootstrap-vue';
import { BCard } from 'bootstrap-vue';
import { BCardText } from 'bootstrap-vue';
import { BCardGroup } from 'bootstrap-vue';
import { BTabs } from 'bootstrap-vue';
import { BTab } from 'bootstrap-vue';
import { BFormSelect } from 'bootstrap-vue';
import { SidebarPlugin } from 'bootstrap-vue';
import { BImg } from 'bootstrap-vue';
import { BSpinner } from 'bootstrap-vue';
import { BOverlay } from 'bootstrap-vue';
import { BAvatar } from 'bootstrap-vue';
import { BFormTags } from 'bootstrap-vue';

import { BIcon } from 'bootstrap-vue';
import { BootstrapVueIcons } from 'bootstrap-vue';

export function initBootstrapVue(vue) {
  vue.use(BootstrapVueIcons);
  vue.component('b-avatar', BAvatar);
  vue.component('b-form-tags', BFormTags);
  vue.component('b-badge', BBadge);
  vue.component('b-dropdown', BDropdown);
  vue.component('b-dropdown-item', BDropdownItem);
  vue.component('b-link', BLink);
  vue.component('b-alert', BAlert);
  vue.component('b-modal', BModal);
  vue.component('b-button', BButton);
  vue.component('b-navbar', BNavbar);
  vue.component('b-navbar-nav', BNavbarNav);
  vue.component('b-navbar-brand', BNavbarBrand);
  vue.component('b-navbar-toggle', BNavbarToggle);
  vue.component('b-pagination', BPagination);
  vue.component('b-progress', BProgress);
  vue.component('b-progress-bar', BProgressBar);
  vue.component('b-form', BForm);
  vue.component('b-form-input', BFormInput);
  vue.component('b-form-group', BFormGroup);
  vue.component('b-form-checkbox', BFormCheckbox);
  vue.component('b-form-checkbox-group', BFormCheckboxGroup);
  vue.component('b-collapse', BCollapse);
  vue.component('b-nav-item', BNavItem);
  vue.component('b-nav-item-dropdown', BNavItemDropdown);
  vue.component('b-form-textarea', BFormTextarea);
  vue.component('b-card', BCard);
  vue.component('b-card-text', BCardText);
  vue.component('b-card-group', BCardGroup);
  vue.component('b-tabs', BTabs);
  vue.component('b-tab', BTab);
  vue.component('b-form-select', BFormSelect);
  vue.component('b-img', BImg);
  vue.component('b-spinner', BSpinner);
  vue.component('b-icon', BIcon);
  vue.component('b-overlay', BOverlay);
  vue.use(SidebarPlugin);
  vue.directive('b-modal', VBModal);
}
